site_name: Tobias makes docs

theme:
    name: material
    custom_dir: docs/theme_override_home/
    features:
        - content.tabs.link
        - content.code.annotate
        - toc.integrate
    icon:
        admonition:
        <type>: <icon>
nav:
    - Opic: opic.md          
    # - Technologies:
    #       - "Section1": "guide/index3.md"
    #       - "Section2": "guide/index4.md"

markdown_extensions:
    - pymdownx.tabbed:
          alternate_style: true
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true

extra_css:
  - stylesheets/extra.css

markdown_extensions:
    - tables
    - abbr
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.highlight:
          anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences:
          custom_fences:
              - name: mermaid
                class: mermaid
                format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.details
    - footnotes
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - def_list
    - pymdownx.tasklist:
          custom_checkbox: true
